### ISSUE TITLE
example Tutorial_Calcium.py error

### ISSUE THREAD

**Issue by samuelandjw** [robclewley/pydstool#103]
Mac OS 10.10.3, Python 3.4 installed through homebrew. pydstool version: github repo master branch latest
For `Tutorial_Calcium.py`, the first two figures came out fine, but the last line `PC['SN1'].display(['i','gca'], figure=4)` produced the following error message:
```
LP Point found 
LP Point found 
CP Point found 
Exception ignored in: <bound method Vode_ODEsystem.__del__ of Generator Calcium channel model>
Traceback (most recent call last):
  File "/Users/wudegang/pydstool/PyDSTool/Generator/Vode_ODEsystem.py", line 922, in __del__
  File "/Users/wudegang/pydstool/PyDSTool/Generator/ODEsystem.py", line 525, in __del__
  File "/Users/wudegang/pydstool/PyDSTool/Generator/baseclasses.py", line 1404, in __del__
  File "/Users/wudegang/pydstool/PyDSTool/Generator/baseclasses.py", line 1356, in __del__
SyntaxError: unexpected EOF while parsing (<string>, line 0)
```

**Comment by z2v** [comment]
@robclewley, what's the point in implementing [`__del__`](https://docs.python.org/2/reference/datamodel.html#object.__del__) methods?

**Comment by robclewley** [comment]
It has been a very long time since I put those things together, but I recall the del methods are there to support the correct functioning of the tear-down process when the class has dynamically-added methods (see `__getstate__`). Or, at least, that was how it was recommended to me back then. Maybe it's no longer the best/right/necessary way to do it. I recall that, unless the object attributes containing dynamically created methods are explicitly deleted in this way, the marshalling done as part of a deep copy() will fail. Those attributes are reconstructed by `__setstate__` during un-marshalling.

**Comment by robclewley** [comment]
I can't yet understand what would lead to this SyntaxError only on one platform. Perhaps @samuelandjw can insert some print statements for us throughout the baseclass `Generator.__del__` method (within the try-except clause) to pinpoint which part is breaking. It's very odd and I have no way to reproduce this.

**Comment by samuelandjw** [comment]
I have just checked out the latest files in the master branch, and the line numbers in the error message has changed to:
```
  File "/usr/local/lib/python3.4/site-packages/PyDSTool-0.90.0-py3.4.egg/PyDSTool/Generator/Vode_ODEsystem.py", line 923, in __del__
  File "/usr/local/lib/python3.4/site-packages/PyDSTool-0.90.0-py3.4.egg/PyDSTool/Generator/ODEsystem.py", line 525, in __del__
  File "/usr/local/lib/python3.4/site-packages/PyDSTool-0.90.0-py3.4.egg/PyDSTool/Generator/baseclasses.py", line 1430, in __del__
  File "/usr/local/lib/python3.4/site-packages/PyDSTool-0.90.0-py3.4.egg/PyDSTool/Generator/baseclasses.py", line 1381, in __del__
```
The statement that causes the error is the last statement (line 1381):
```
    def __del__(self):
        # delete object-specific class methods etc. before deleting
        # to avoid crowding namespace
        try:
            for fname, finfo in self._funcreg.items():
                try:
                    delattr(eval(finfo[0]), fname)
```
I added a print statement to see what is going on:
```
                try:
                    print(finfo[0], fname)
                    delattr(eval(finfo[0]), fname)
```
and I got
```
self _solver
self _auxfn_minf
self _auxfn_getbound
 minf
```
It seems that in the 4th iteration, finfo[0] is an empty string.
Hope this helps.

**Comment by robclewley** [comment]
@samuelandjw Thanks, that helps. If I understand correctly, this error text is displayed but is not actually responsible for stopping execution because it's suppressed inside `__del__`. If that's *not* the case, then this will be a more urgent issue.

**Comment by samuelandjw** [comment]
@robclewley The error was reported after all the statements had been executed, and the debugger (I'm using PyCharm 4) could not even get into __del__, so I guess it actually did not stop the execution of any  statements in the example.
