### ISSUE TITLE
Error in PyCont_LPNeuron.py - not finding Hopf points

### ISSUE THREAD

**Issue by tmchartrand** [robclewley/pydstool#109]
I'm running the latest pydstool from master here, and getting an error running PyCont_LPNeuron.py:
The final error is 
  File "/usr/local/lib/python2.7/dist-packages/PyDSTool-0.90.0-py2.7.egg/PyDSTool/PyCont/ContClass.py", line 167, in newCurve
    raise KeyError('No point of name ' + pointname + ' exists.')
KeyError: 'No point of name H1 exists.'

What seems to be happening is that the Hopf points are not being found during the continuation, I'm just seeing a bunch of "Test function going crazy:  class Hopf_Bor(BorderMethod, BiAltMethod)"

Here's the resulting diagram, I'm not sure if the continuation is just not going far enough to see the Hopf point or whether the issue is with detecting them:

![diag](https://cloud.githubusercontent.com/assets/12821536/8094679/68d5a742-0f7d-11e5-957b-a1c6d666b02e.png)

**Comment by tmchartrand** [comment]
Really strange - now I can't reproduce myself! seems to work fine...
Only possibility I can think of is that it had something to do with running other examples in a specific order beforehand (was just testing a few randomly one by one).

**Comment by robclewley** [comment]
Thanks for the info. It works for me with the github version (try updating) on python 2.7, and your P1 looks very close to where the Hopf point is.

For the time being, please also post this on the sourceforge help forum where there are advanced users (and devs) keeping track of new posts. We are very slowly transitioning from that system, and I know that's not very clear, but I think you'll want to get input from those folk more than me.
