### ISSUE TITLE
shared variables in an hybrid model

### ISSUE THREAD

**Issue by hibarikyouya** [robclewley/pydstool#117]
Hello,

First of all thank you very much for developping PyDSTool.

Is it possible to share variables between two submodels in an hybrid system ?
For example, I have a model1 and a model2.
I define a condition, or an event, to switch from the model1 to the model2.
The initial conditions for the model2 have to be fixed, but, at the moment of the switch, would it possible that the model2 takes the output values of the model1 as an input ?

Thank you.

**Comment by robclewley** [comment]
Hi. I think it's usually *expected* to share variables between sub-models, so that they can communicate and transition from one state to another. The integrate-and-fire model does exactly the kind of behavior you describe, if I understand you correctly. Please see the examples provided in the download and read about this setup in the [tutorial](http://www.ni.gsu.edu/~rclewley/PyDSTool/Tutorial/Tutorial_hybrid.pdf)

**Comment by hibarikyouya** [comment]
Thank you very much Rob.

Of course I already read it :)
You have to define initial conditions for each submodels.
From what I understood you cannot make a submodel take the output of another submodel as an initial condition.

**Comment by robclewley** [comment]
I think if you showed me what model you're trying to build, I'd understand your issue better. But you can access the IC of a variable using the `initcond(<var>)` function.

**Comment by hibarikyouya** [comment]
Hi,

Thank you for your answer.
I am trying to do something like the code below, but I cannot event achieve this simple example.
The idea was to make the model2 take the last value of the varC when the threshold1 is reach.
Can I put my post in the help section of sourceforge ?
Thank you

`from PyDSTool import *

model1 = args(name="model1")
model2 = args(name="model2")

model1.pars = { 'kA':4, 'kC':1, 'threshval1':2}
model2.pars = { 'kB':4, 'kC':1, 'threshval2':2}

model1.ics = { 'varA':0, 'varC':10 }
model2.ics = { 'varB':0, 'varC':10 }

model1.varspecs = { 'varA':'kA', 'varC':'-kC' }
model2.varspecs = { 'varB':'kB', 'varC':'-kC' }

model1.xdomain = {'varA':[-100,100], 'varC':[-100,100]}
model2.xdomain = {'varB':[-100,100], 'varC':[-100,100]}

event_args_1 = {'name':'threshold1', 'eventtol':1e-3, 'eventdelay':1e-4,
        'term':True}
thresh_ev_1 = makeZeroCrossEvent('varA-threshval1', 1, event_args_1,
        varnames=['varA'], parnames=['threshval1'])
model1.events = thresh_ev_1

event_args_2 = {'name':'threshold2', 'eventtol':1e-3, 'eventdelay':1e-4,
        'term':True}
thresh_ev_2 = makeZeroCrossEvent('varB-threshval2', 1, event_args_2,
        varnames=['varB'], parnames=['threshval2'])
model2.events = thresh_ev_2

model1.tdata = [0,10]
model2.tdata = [0,10]

ds1 = embed(Generator.Vode_ODEsystem(model1), name="model1")
ds2 = embed(Generator.Vode_ODEsystem(model2), name="model2")

all_names = ['model1', 'model2']

mi_1 = intModelInterface(ds1)
mi_2 = intModelInterface(ds2)

info_1 = makeModelInfoEntry(mi_1, all_names, [('threshold1', 'model2')])
info_2 = makeModelInfoEntry(mi_2, all_names, [('threshold2', 'model1')])

modelInfoDict = makeModelInfo([info_1, info_2])
mod_args = {'name':'model', 'modelInfo':modelInfoDict}

model = Model.HybridModel(mod_args)
model.tdata = [0,2]
model.compute(trajname='test', tdata=[0,3])
`

**Comment by hibarikyouya** [comment]
Sorry I had not read properly.
I was looking the `EvMapping` class
