### ISSUE TITLE
Hopf bifurcation broken with recent numpy version

### ISSUE THREAD

**Issue by celliern** [robclewley/pydstool#126]
This is linked with the division in the `PyDSTool.PyCont.TestFunc.BiAltMethod`, in the three method of the class.

I suspect a incomplete migration from py2, and using a float in numpy indexes throw an error on the recent versions. (It was just a DeprecationWarning before).

Using `//` or `int()` should fix the errors.

**Comment by z2v** [comment]
Must be fixed in current master.
