### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by willfurnass** [robclewley/pydstool#143]
Would be good to get a new release on PyPI given that there have been many changes since the 0.90.2 release (between 0e33c951 and d43a9fbec21e11cab9b4b1cb7bc6912b91f419e1), with the support for newer scipy/numpy releases and dropping support for Python<3.6 both being fairly significant.

**Comment by z2v** [comment]
Done https://pypi.org/project/PyDSTool/#files
