### ISSUE TITLE
Import of pydstool fails with scipy 1.4.1

### ISSUE THREAD

**Issue by dabliss** [robclewley/pydstool#148]
Here's the error message I get:

/home/dan/bliss-distributed-wm/mejias/mejias_ei_local_phaseplane.py in <module>()
      2 import pickle
      3 
----> 4 import PyDSTool as dst
      5 from PyDSTool.Toolbox import phaseplane as pp
      6 import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/__init__.py in <module>()
     56 
     57 # PyDSTool imports
---> 58 from .Events import *
     59 from .Interval import *
     60 from .Points import *

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/Events.py in <module>()
     10 
     11 # PyDSTool imports
---> 12 from .Variable import *
     13 from .utils import *
     14 from .common import *

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/Variable.py in <module>()
     12 from .Points import *
     13 from .Interval import *
---> 14 from .FuncSpec import ImpFuncSpec
     15 
     16 from numpy import Inf, NaN, isfinite, sometrue, alltrue, any, all, \

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/FuncSpec.py in <module>()
     14 from .errors import *
     15 from .utils import info as utils_info
---> 16 from .Symbolic import QuantSpec, allmathnames_symbolic
     17 
     18 # Other imports

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/Symbolic.py in <module>()
    174 
    175 # REGULAR VERSION
--> 176 funcnames = [n for n in allmathnames if hasattr(eval(modlookup[n]+n),
    177                                                 "__call__")]
    178 

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/Symbolic.py in <listcomp>(.0)
    174 
    175 # REGULAR VERSION
--> 176 funcnames = [n for n in allmathnames if hasattr(eval(modlookup[n]+n),
    177                                                 "__call__")]
    178 

/usr/local/lib/python3.6/dist-packages/PyDSTool-0.90.3-py3.6.egg/PyDSTool/Symbolic.py in <module>()

AttributeError: module 'scipy.special' has no attribute 'hyp2f0'

**Comment by dabliss** [comment]
Import of pydstool is successful with scipy 1.3.0.  I haven't tried other versions.

**Comment by willfurnass** [comment]
That scipy function was removed in scipy 1.4.0: https://docs.scipy.org/doc/scipy/reference/release.1.4.0.html  See also https://github.com/scipy/scipy/issues/8443

**Comment by dabliss** [comment]
I just submitted a pull request that resolves this issue.  Thanks, @willfurnass.

**Comment by z2v** [comment]
Fixed with e3e8c7dba4d0a66b119a9099eb0be06952345921
