### ISSUE TITLE
Using a custom function to find fix points

### ISSUE THREAD

**Issue by ulyssek** [robclewley/pydstool#154]
Hi there,

And thanks for this amazing package. I'm using it to find phase plane for my system, but I'd like to use a custom function.

Here's what I'm doing : 

```

## imports
from PyDSTool.Toolbox import phaseplane as pp
import PyDSTool as dst


##  Creating the Vode_ODEsystem
params = {
    'my_custom_function' : np.array([0,1,2]) ## Here's where I'm using a custom function, in the form of a numpy array
}

domains = {
    'x' : [0,1],
    'y' : [0,1],
}

functions =  {
    'foo' : (['z'], 'my_custom_function[int(2*z)]'), ## This line is not working
}

eqs = {
        'x' : '-2 * x + foo(x)',
        'y' : '- y',
}

DSargs = dst.args(name='my_model')

DSargs.pars = params
    
DSargs.fnspecs = functions

DSargs.varspecs = eqs

DSargs.tdomain = [0, 30]
    
DSargs.xdomain = domains

dmModel = dst.Vode_ODEsystem(DSargs)

## Finding the fix points
pp.find_fixedpoints(dmModel, n=4, eps=1e-8)
```

But this is not working, do you have any clue about what I could do here?

Thanks a lot,

**Comment by robclewley** [comment]
Hi.

Could you be very specific on exactly what the error / incorrect behavior
is?

By eye, it looks like you're trying to set a numpy array as an individual
parameter, which isn't a valid thing to do. Parameters are real numbers
only. For VODE only, you can use the array as a literal in the function
definition instead of by a name. I think there's an example of using numpy
names inside of functions like that in one of the demo scripts bundled with
the package.

**Comment by ulyssek** [comment]
When I try this, I have the following error : 

`TypeError: only size-1 arrays can be converted to Python scalars`

Obviously, Pydstool expect me to use scalars as parameters.


Could you send me the link to the demo script? I couldn't find it in the doc.


Thanks a lot

**Comment by robclewley** [comment]
Here you go. This is a hack to allow arbitrary code into your RHS,
drawbacks being it is less structured and specific to the target language.
E.g. if you wanted to run with Dopri or Radau, you'd have to re-implement
the `foo` function in C.

Note that you don't need numpy here at all. A python list literal takes
care of what you need.

```
from PyDSTool.Toolbox import phaseplane as pp
import PyDSTool as dst

domains = {
    'x' : [0,1],
    'y' : [0,1],
}

eqs = {
        'x' : '-2 * x + foo(x)',
        'y' : '- y',
}

DSargs = dst.args(name='my_model')

DSargs.vfcodeinsert_start = """
def foo(z):
      return [0,1,2][int(2*z)]
"""
DSargs.varspecs = eqs
DSargs.ignorespecial = ['foo']
DSargs.tdomain = [0, 30]

DSargs.xdomain = domains

dmModel = dst.Vode_ODEsystem(DSargs)

pp.find_fixedpoints(dmModel, n=4, eps=1e-8)
```

Note that the pre-processing of indented code's whitespace isn't great in
vfcodeinsert, so all of those indentation spaces are needed to get it to
parse. Alternatively, you could skip the function and replace the middle
part of this with

```
eqs = {
        'x' : '-2 * x + z',
        'y' : '- y',
}

DSargs = dst.args(name='my_model')

DSargs.vfcodeinsert_start = """
z = [0,1,2][int(2*x)]
"""
DSargs.varspecs = eqs
DSargs.ignorespecial = ['z']
```

**Comment by robclewley** [comment]
PS. I don't know if that was your intended final system or a demonstrative
example, but [0,1,2] is redundant in this example since its values are
exactly the same as its indices.

**Comment by ulyssek** [comment]
Amazing, it's working perfectly. Thanks a lot!


PS. it was a demonstrative example, my_custom_function is a 1000 x 1000 2D precomputed numpy array.

**Comment by ulyssek** [comment]
Hi, it's me again!

This hack doesn't work to find nullclines, which is one of my goals:


```
from PyDSTool.Toolbox import phaseplane as pp
import PyDSTool as dst

domains = {
    'x' : [0,1],
    'y' : [0,1],
}

eqs = {
        'x' : '-2 * x + foo(x)',
        'y' : '- y',
}

DSargs = dst.args(name='my_model')

DSargs.vfcodeinsert_start = """
def foo(z):
      return [0,1,2][int(2*z)]
"""
DSargs.varspecs = eqs
DSargs.ignorespecial = ['foo']
DSargs.tdomain = [0, 30]

DSargs.xdomain = domains

dmModel = dst.Vode_ODEsystem(DSargs)

fp_coord = pp.find_fixedpoints(dmModel, n=4, eps=1e-8)

pp.find_nullclines(dmModel, *list(eqs.keys()), n=3, eps=1e-8,
                                          max_step=0.01, fps=fp_coord)
```

This code is basically the same as the one above, except that I use the fixed points to compute the nullclines.

I now have the following error : 
```
ValueError: Undeclared or illegal token `foo` in spec string `x`
```

**Comment by robclewley** [comment]
Closing this as the merge should have fixed the issue.

**Comment by ulyssek** [comment]
Yes, working perfectly, thanks a lot!
