### ISSUE TITLE
PyCont examples are broken

### ISSUE THREAD

**Issue by z2v** [robclewley/pydstool#21]
After PyCont update (commit 42b8acdd9be41accaed1535b8de0e8854fdc21ea) these PyCont examples are broken:
- PyCont_Catalytic.py
- PyCont_DiscPredPrey.py
- PyCont_Hopfield.py
- PyCont_Logistic.py
- PyCont_MorrisLecar_TypeI.py
- PyCont_MorrisLecar_TypeII.py
- PyCont_LPNeuron.py
- PyCont_HindmarshRose.py
- PyCont_ABReaction.py
- PyCont_Hamiltonian.py
- PyCont_Lorenz.py
- PyCont_vanDerPol.py

**Comment by jckegelman** [comment]
Also just for the record, these examples are broken in my environment:

- PyCont_Hopfield.py
- PyCont_Logistic.py

which produce the following errors:

```
Traceback (most recent call last):
  File "PyCont_Logistic.py", line 58, in <module>
    PCargs.initdirec = PyCont['FP2'].getSpecialPoint('PD1').labels['PD']['data'].branch
AttributeError: 'NoneType' object has no attribute 'labels'
```
```
Traceback (most recent call last):
  File "PyCont_Hopfield.py", line 89, in <module>
    PyCont['FO1'].backward()
  File "/home/kegelman/repos/pydstool/PyDSTool/PyCont/Continuation.py", line 1435, in backward
    for k, v in pt.labels[ctype]['data'].V.items():
KeyError: 'LP'
```

**Comment by z2v** [comment]
Current examples problems are collected in #101.
