### ISSUE TITLE
Sync versions everywhere

### ISSUE THREAD

**Issue by z2v** [robclewley/pydstool#92]
There is little divergence in mentioned PyDSTool versions:
* [Homepage](http://www.ni.gsu.edu/~rclewley/PyDSTool/FrontPage.html): 0.90
* [Pypi](https://pypi.python.org/pypi/PyDSTool): 0.90.0
* [Github](https://github.com/robclewley/pydstool/releases): 0.90.0
* [SourceForge](https://sourceforge.net/projects/pydstool/): 0.90.1 (!)

So I suggest add `0.90.1` tag in repo on proper revision, upload new release on PyPi and update version on homepage.

**Comment by robclewley** [comment]
Yes, let me finish testing the recent bugfixes and updates to the toolbox and then we'll make it 0.90.2 everywhere.

**Comment by robclewley** [comment]
@z2v do you have any other additions you'd like to see in the new tagged release? I want to address the broken examples before completing this.

**Comment by z2v** [comment]
@robclewley, no.

**Comment by robclewley** [comment]
Closed with release of v0.90.2
